main: dev.laarryy.playerheads.PlayerHeads
name: PlayerHeads
version: "4.2"
api-version: "1.15"
commands:
  playerheads:
    description: "Add playerheads to the game."
    usage: "Usage: /playerheads give [PlayerName] {Amount} or /playerheads spawntrader [x] [y] [z] or /playerheads removetrader or /playerheads get [Base64] {Amount} {DisplayName}"
permissions:
  vendettacraft.playerheads.*:
    description: "Allows you to use all the commands in this plugin."
    default: "op"
  vendettacraft.playerheads.give:
    description: "Allows you to use /playerheads give [PlayerName] {Amount}."
    default: "op"
  vendettacraft.playerheads.spawntrader:
    description: "Allows you to use /playerheads spawntrader [x] [y] [z]."
    default: "op"
  vendettacraft.playerheads.removetrader:
    description: "Allows you to use /playerheads removetrader."
    default: "op"
  vendettacraft.playerheads.get:
    description: "Allows you to use /playerheads get [Base64] {Amount} {DisplayName}."
    default: "op"